---
title: "LendingData"
author: "Mohamed"
date: "5/16/2018"
output:
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(WDI)
library(RItools)
library(pdftools)
library(tibble)
library(tidyr)
library(reshape2)
library(readxl)
library(openxlsx)
library(foreign)
library(plyr)
library(dplyr)
Sys.setlocale("LC_ALL","C")
```

```{r, include=FALSE}
LendingDataI <- read.csv("~/Documents/Margin Algo/LoansLarry.csv")

summary(LendingDataI$loan_status)

LendingDataI$loan_status[grep("Does not meet the credit policy. Status:Fully", LendingDataI$loan_status)] <- "Fully Paid"

LendingDataI$loan_status[grep("Does not meet the credit policy. Status:Charged", LendingDataI$loan_status)] <- "Charged Off"

LendingDataI$Repayment <- 0
LendingDataI$Repayment[grep("Fully Paid", LendingDataI$loan_status)] <- 1

LendingDataI$term <- gsub(' months',"", LendingDataI$term, fixed = TRUE)

LendingDataI$grade <- as.factor(LendingDataI$grade)
LendingDataI$sub_grade <- as.factor(LendingDataI$sub_grade)
LendingDataI$term <- as.numeric(LendingDataI$term)
LendingDataI$installment <- as.numeric(LendingDataI$installment)
LendingDataI$int_rate <- as.numeric(LendingDataI$int_rate)
LendingDataI$loan_amnt <- as.numeric(LendingDataI$loan_amnt)
LendingDataI$funded_amnt <- as.numeric(LendingDataI$funded_amnt)
LendingDataI$funded_amnt_inv <- as.numeric(LendingDataI$funded_amnt_inv)
LendingDataI$emp_length <- as.factor(LendingDataI$emp_length)
LendingDataI$home_ownership <- as.factor(LendingDataI$home_ownership)
LendingDataI$annual_inc <- as.numeric(LendingDataI$annual_inc)
LendingDataI$dti <- as.numeric(LendingDataI$dti)
LendingDataI$open_acc <- as.numeric(LendingDataI$open_acc)
LendingDataI$pub_rec <- as.numeric(LendingDataI$pub_rec)
LendingDataI$revol_bal <- as.numeric(LendingDataI$revol_bal)
LendingDataI$revol_util <- as.numeric(LendingDataI$revol_util)
LendingDataI$total_acc <- as.numeric(LendingDataI$total_acc)
LendingDataI$total_pymnt <- as.numeric(LendingDataI$total_pymnt)
LendingDataI$total_pymnt_inv <- as.numeric(LendingDataI$total_pymnt_inv)
LendingDataI$total_rec_prncp <- as.numeric(LendingDataI$total_rec_prncp)
LendingDataI$total_rec_int <- as.numeric(LendingDataI$total_rec_int)
LendingDataI$recoveries <- as.numeric(LendingDataI$recoveries)


LendingPersonal <- LendingDataI[grep("^Personal", LendingDataI$title, ignore.case = TRUE, fixed = FALSE),]

summary(LendingPersonal$loan_status)
summary(LendingPersonal$Repayment)
summary(LendingPersonal$purpose)
head(LendingPersonal$Repayment)
```

```{r, include=FALSE}
## Algo Repayment -- Personal Loans

m1 <- lm(Repayment ~ loan_amnt + funded_amnt + funded_amnt_inv + term + int_rate + installment + grade + sub_grade + emp_length + home_ownership + annual_inc + dti + open_acc + revol_bal + pub_rec + revol_util + total_acc + total_pymnt + total_pymnt_inv + total_rec_int + total_rec_prncp + recoveries, data=LendingPersonal)
step(m1, direction="backward")


m2 <- lm(Repayment ~ funded_amnt + total_rec_prncp, data = LendingPersonal, family=binomial)

m3 <- lm(Repayment ~ loan_amnt + term + int_rate + grade + emp_length + home_ownership + annual_inc + dti, data=LendingPersonal)
```

```{r}
## Repayment Algorithms for Personal Loans
summary(m1)
summary(m2)
summary(m3)
```

```{r, include=FALSE}
## Algo Repayment -- Overall

m4 <- lm(Repayment ~ loan_amnt + funded_amnt + funded_amnt_inv + term + int_rate + installment + grade + sub_grade + emp_length + home_ownership + annual_inc + dti + open_acc + revol_bal + pub_rec + revol_util + total_acc + total_pymnt + total_pymnt_inv + total_rec_int + total_rec_prncp + recoveries, data=LendingDataI)
step(m1, direction="backward")

m5 <- lm(Repayment ~ loan_amnt + revol_util + dti + total_pymnt_inv + annual_inc + funded_amnt_inv + int_rate + pub_rec + emp_length + term + sub_grade + installment + total_rec_int + recoveries + total_pymnt + total_rec_prncp + funded_amnt, data = LendingDataI)

m6 <- lm(Repayment ~ loan_amnt + term + int_rate + grade + emp_length + home_ownership + annual_inc + dti, data=LendingDataI)
```

```{r}
## Repayment Algorithms for General Loans
summary(m4)
summary(m5)
summary(m6)
```

